# Generated by Django 5.2.7 on 2025-10-06 05:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
