# Generated by Django 5.2.7 on 2025-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_memes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='image',
        ),
        migrations.AddField(
            model_name='memes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='memes',
            name='language',
            field=models.CharField(blank=True, choices=[('telugu', 'Tel'), ('english', 'Eng')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memes',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=50, null=True),
        ),
    ]
