# Generated by Django 5.2.7 on 2025-10-06 06:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_memes_image_memes_file_memes_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
