# Generated by Django 5.2.7 on 2025-10-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_memes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
