name: Django CI/CD to EC2 with Supervisor

on:
  push:
    branches: [ main ]  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match your project Python version

      # Step 3: Install dependencies on runner (optional)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Navigate to your project folder
            cd /home/ubuntu/memes_app
            
            # Force update repo to match GitHub
            git fetch origin main
            git reset --hard origin/main

            # Activate virtual environment
            source /home/ubuntu/venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Apply migrations and collect static files
            python3 manage.py makemigrations --noinput
            python3 manage.py migrate --noinput
            python3 manage.py collectstatic --noinput

            # Restart Supervisor program
            sudo supervisorctl restart guni:gunicorn
